// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwalAMOI9q_tzKzbVAMHK9y2-vvxbYRQ',
    appId: '1:975056194033:web:13e77a1fbdb1dc5330dc50',
    messagingSenderId: '975056194033',
    projectId: 'away-6daf3',
    authDomain: 'away-6daf3.firebaseapp.com',
    storageBucket: 'away-6daf3.firebasestorage.app',
    measurementId: 'G-76LXB5YHF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnXaT48KD3HsVIlVZzdasK_bA6Oi7eVAU',
    appId: '1:975056194033:android:23079be898a3f50f30dc50',
    messagingSenderId: '975056194033',
    projectId: 'away-6daf3',
    storageBucket: 'away-6daf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQA1g-1TUc2DOzU2smLBfRr67Mcie0kU',
    appId: '1:975056194033:ios:b1ecf75cbe47756e30dc50',
    messagingSenderId: '975056194033',
    projectId: 'away-6daf3',
    storageBucket: 'away-6daf3.firebasestorage.app',
    iosBundleId: 'com.example.awayAppV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhQA1g-1TUc2DOzU2smLBfRr67Mcie0kU',
    appId: '1:975056194033:ios:b1ecf75cbe47756e30dc50',
    messagingSenderId: '975056194033',
    projectId: 'away-6daf3',
    storageBucket: 'away-6daf3.firebasestorage.app',
    iosBundleId: 'com.example.awayAppV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbwalAMOI9q_tzKzbVAMHK9y2-vvxbYRQ',
    appId: '1:975056194033:web:c71774c96cc4f25330dc50',
    messagingSenderId: '975056194033',
    projectId: 'away-6daf3',
    authDomain: 'away-6daf3.firebaseapp.com',
    storageBucket: 'away-6daf3.firebasestorage.app',
    measurementId: 'G-H6R4EM0EX1',
  );
}
